#https://help.sonatype.com/display/NXI/CloudFormation+-+Repository+Manager
AWSTemplateFormatVersion: '2010-09-09'
Description: Nexus Repository Manager Minimal Configuration Stack.
Mappings:
  AmiRegionMap:
    ap-southeast-2:
      centos7: ami-24959b47
      xenial: ami-bb1901d8
    eu-central-1:
      centos7: ami-7cbc6e13
      xenial: ami-958128fa
    eu-west-1:
      centos7: ami-0d063c6b
      xenial: ami-674cbc1e
    us-east-1:
      centos7: ami-ae7bfdb8
      xenial: ami-1d4e7a66
    us-east-2:
      centos7: ami-9cbf9bf9
      xenial: ami-dbbd9dbe
    us-west-2:
      centos7: ami-0c2aba6c
      xenial: ami-8803e0f0
  Defaults:
    ChefRecipeUrl:
      Value: https://github.com/sonatype/chef-nexus-repository-manager/releases/download/release-0.5.20171127-222629.c2a02ed/chef-nexus-repository-manager.tar.gz
    DeleteBlockDeviceOnTermination:
      Value: 'true'
    InstanceType:
      Value: t2.large
    JavaDownloadUrl:
      Value: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/server-jre-8u131-linux-x64.tar.gz
    JavaSha256:
      Value: a80634d17896fe26e432f6c2b589ef6485685b2e717c82cd36f8f747d40ec84b
    LogGroupName:
      Value: ''
    NexusRepositoryManagerSha256:
      Value: 949e2e5e99a685ebce6a63ba1ca0d56bc794068922a5279bca59d15bd3ae677c
    NexusRepositoryManagerVersion:
      Value: 3.8.0-02
    SubnetAz0:
      Value: 10.0.1.0/24
    VpcNetBlock:
      Value: 10.0.0.0/16
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Optional parameters
      Parameters:
      - LicenseS3Bucket
      - LicenseS3Path
      - KeyName
      - TagBuilder
    ParameterLabels:
      KeyName:
        default: Key pair
      LicenseS3Bucket:
        default: License S3 bucket
      LicenseS3Path:
        default: License S3 path
      TagBuilder:
        default: Tag
Outputs:
  LogGroup:
    Value:
      Fn::GetAtt:
      - NestedStack
      - Outputs.LogGroup
  WebsiteURL:
    Value:
      Fn::GetAtt:
      - NestedStack
      - Outputs.WebsiteURL
Parameters:
  KeyName:
    Default: ''
    Description: Your key pair name for this region
    Type: String
  LicenseS3Bucket:
    Default: ''
    Description: (Optional) The S3 Bucket containing your Nexus Repository Manager
      license file
    Type: String
  LicenseS3Path:
    Default: ''
    Description: (Optional) The path to your Nexus Repository Manager license file
      within the S3 Bucket
    Type: String
  TagBuilder:
    Default: ''
    Description: The tag for resources created
    Type: String
Resources:
  NestedStack:
    Properties:
      Parameters:
        ChefRecipeUrl:
          Fn::FindInMap:
          - Defaults
          - ChefRecipeUrl
          - Value
        DeleteBlockDeviceOnTermination:
          Fn::FindInMap:
          - Defaults
          - DeleteBlockDeviceOnTermination
          - Value
        InstanceType:
          Fn::FindInMap:
          - Defaults
          - InstanceType
          - Value
        JavaDownloadUrl:
          Fn::FindInMap:
          - Defaults
          - JavaDownloadUrl
          - Value
        JavaSha256:
          Fn::FindInMap:
          - Defaults
          - JavaSha256
          - Value
        KeyName:
          Ref: KeyName
        LicenseS3Bucket:
          Ref: LicenseS3Bucket
        LicenseS3Path:
          Ref: LicenseS3Path
        LogGroupName:
          Fn::FindInMap:
          - Defaults
          - LogGroupName
          - Value
        NexusRepositoryManagerSha256:
          Fn::FindInMap:
          - Defaults
          - NexusRepositoryManagerSha256
          - Value
        NexusRepositoryManagerVersion:
          Fn::FindInMap:
          - Defaults
          - NexusRepositoryManagerVersion
          - Value
        SubnetAz0:
          Fn::FindInMap:
          - Defaults
          - SubnetAz0
          - Value
        TagBuilder:
          Ref: TagBuilder
        VpcNetBlock:
          Fn::FindInMap:
          - Defaults
          - VpcNetBlock
          - Value
      TemplateURL: https://s3.amazonaws.com/sonatype-cloudformation-templates/nexus-repository-manager/1.0.20180205-183252.3cb2a73/7d47d4a757cd7ca2692de5a9b7542d67.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
