AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: m3.medium
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m2.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - c1.medium
      - c1.xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - g2.2xlarge
      - g2.8xlarge
      - r3.large
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - i2.xlarge
      - i2.2xlarge
      - i2.4xlarge
      - i2.8xlarge
      - d2.xlarge
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge
      - hi1.4xlarge
      - hs1.8xlarge
      - cr1.8xlarge
      - cc2.8xlarge
      - cg1.4xlarge
    Description: Enter instance size. Default is m3.medium.
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and Proxy Ports
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: '3128'
        ToPort: '3128'
        CidrIp: '0.0.0.0/0'
  Linux:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-97785bed
      InstanceType:
        Ref: InstanceTypeParameter
      KeyName: DukeLegion
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      Tags:
        -
          Key: Application
          Value: Squid
        -
          Key: Domain
          Value: None
        -
          Key: Environment
          Value: Test
        -
          Key: LifeTime
          Value: Transient
        -
          Key: Name
          Value: Squid
        -
          Key: OS
          Value: Linux
        -
          Key: OwnerContact
          Value: "#{Deployer Contact}"
        -
          Key: Purpose
          Value: Support Test Instance
        -
          Key: Source
          Value: CloudForation Script in Octopus Deploy
        -
          Key: scheduler:ec2-startstop
          Value: true
      UserData:
        Fn::Base64: |
          #cloud-boothook
          #!/bin/bash
          sudo yum install -y libunwind libicu jq java-1.8.0-openjdk squid httpd-tools krb5-workstation samba-common ntp samba-winbind authconfig samba-winbind-clients dnsmasq
          sudo update-alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
          sudo hostname SQUID
          # Install NodeJS
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install 6.11.5
          sudo cat <<'EOF' > /etc/squid/password
          octopus:$apr1$8NaM.I5W$ElXou1.ks4T.z28kcFn9Y0
          EOF
          sudo cat <<'EOF' > /home/ec2-user/adconnect.sh
          authconfig --enableshadow --enablemd5 --passalgo=md5 --krb5kdc=EC2AMAZ-AJTKO0B.Octopus.Test \
          --krb5realm=Octopus.Test --smbservers=EC2AMAZ-AJTKO0B.Octopus.Test --smbworkgroup=OCTOPUS \
          --enablewinbind --enablewinbindauth --smbsecurity=ads --smbrealm=Octopus.Test \
          --smbidmapuid="16777216-33554431" --smbidmapgid="16777216-33554431" --winbindseparator="+" \
          --winbindtemplateshell="/bin/false" --enablewinbindusedefaultdomain --disablewinbindoffline \
          --winbindjoin=administrator --disablewins --disablecache --enablelocauthorize --updateall
          EOF
          sudo chmod +x /home/ec2-user/adconnect.sh
          sudo cat <<'EOF' > /etc/squid/squid.conf
          http_port 3128
          # Custom DNS Server Example
          #dns_nameservers 127.0.0.1
          # Domain Blocking Example
          #acl toblock dstdomain .amazonaws.com
          #http_access deny toblock
          # BASIC AUTH SETTINGS
          auth_param basic program /usr/lib64/squid/basic_ncsa_auth /etc/squid/password
          auth_param basic realm proxy
          acl authenticated proxy_auth REQUIRED
          http_access allow authenticated
          # NTLM SETTINGS
          #auth_param ntlm program /usr/bin/ntlm_auth --helper-protocol=squid-2.5-ntlmssp
          #auth_param ntlm children 5
          #auth_param ntlm keep_alive on
          #acl ntlm proxy_auth REQUIRED
          #http_access allow ntlm
          EOF
          sudo service squid start
          sudo chkconfig squid on
Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
      - Linux
      - PublicIp
    Description: Server's PublicIp Address
