AWSTemplateFormatVersion: 2010-09-09
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and Web POrts
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: '0.0.0.0/0'
  Tomcat:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-f2efe388
      InstanceType: m3.medium
      KeyName: DukeLegion
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      Tags:
        -
          Key: Appplication
          Value: Tomcat
        -
          Key: Domain
          Value: None
        -
          Key: Environment
          Value: Test
        -
          Key: LifeTime
          Value: Transient
        -
          Key: Name
          Value: Tomcat
        -
          Key: OS
          Value: Linux
        -
          Key: OwnerContact
          Value: "#{Contact}"
        -
          Key: Purpose
          Value: Support Test Instance
        -
          Key: Source
          Value: CloudForation Script in Octopus Deploy
        -
          Key: scheduler:ec2-startstop
          Value: true
      UserData:
        Fn::Base64: |
          #cloud-boothook
          #!/bin/bash
          echo "Starting" > /tmp/cloudhook
          sudo apt-get --assume-yes update
          sudo apt-get --assume-yes install curl libunwind8 gettext apt-transport-https jq
          if [ ! -f /opt/bitnami/apache-tomcat/credentials.txt ]; then
            sudo grep -oP "(?<=Bitnami application password to ')[^']+" /var/log/syslog > /opt/bitnami/apache-tomcat/credentials.txt
            sudo chown tomcat:tomcat /opt/bitnami/apache-tomcat/credentials.txt
            sudo chmod 600 /opt/bitnami/apache-tomcat/credentials.txt
          fi
Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
      - Tomcat
      - PublicIp
    Description: Server's PublicIp Address